version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      - DB_SERVER_HOST=postgresql
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop
  web:
    image: python:3.6
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
#    command: ls -lah
    volumes:
      - ./src/shop/:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
